# Add application configuration variables here, as shown below.
#
# PUSHER_APP_ID: "2954"
# PUSHER_KEY: 7381a978f7dd7f9a1117
# PUSHER_SECRET: abdc3b896a0ffb85d373
# STRIPE_API_KEY: EdAvEPVEC3LuaTg5Q3z6WbDVqZlcBQ8Z
# STRIPE_PUBLIC_KEY: pk_BRgD57O8fHja9HxduJUszhef6jCyS

development:
    FACEBOOK_APP_ID: 168831249938144
    FACEBOOK_SECRET: 4ed711468bf1e7067f0c3a417a39569a
    LINKEDIN_API_KEY: mky987r927xk
    LINKEDIN_SECRET_KEY: J6mdxQRCxLzFylVG

production:
    FACEBOOK_APP_ID: 168831249938144
    FACEBOOK_SECRET: 4ed711468bf1e7067f0c3a417a39569a
    LINKEDIN_API_KEY: mky987r927xk
    LINKEDIN_SECRET_KEY: J6mdxQRCxLzFylVG